C++: Fix clang tidy build (#393)
The clang tidy build is failing on PR #383, with an error:

server.hpp:85:11: error: field has incomplete type 'Context'

Oddly, it's not failing in my local environment (with clang 19.1.7),
nor is it failing on main (with clang 18.1.3). Something must be cursed,
but I can't figure out what.

This change also removes some unused includes.